### ISSUE TITLE
Can't load plugin since version 2.1.2

### ISSUE THREAD

**Issue by codeurimpulsif** [pelican-plugins/yaml-metadata#9]
All is working in version `2.1.1`, but since I updated to version `2.1.2` it can't load:

```bash
$ make html
[16:35:12] ERROR    Cannot load plugin `yaml_metadata`        log.py:94
                    Cannot import plugin `yaml_metadata`
```

**Comment by justinmayer** [comment]
I'd like to assist you, but there isn't anywhere near enough information in this issue to even begin to help you.

Start here: https://docs.getpelican.com/en/latest/contribute.html#how-to-get-help

As a side note, when I run `python -m pip install pelican-yaml-metadata` and then `pelican-plugins`, I see:

    Plugins found:
    pelican.plugins.yaml_metadata

So, at this point, I have no reason to think there is any problem with v2.1.2 of this plugin.

**Comment by codeurimpulsif** [comment]
Oh my bad, it seems the dependency in my `requirements.txt` was this github repository and not the exact release version :facepalm: 

I close this issue, sorry for the noise.
